### ISSUE TITLE
sin / cos discrepancy with javascript

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-common-packages#51]
We have fixed point aritmetic sine/cos ported from AVR. Not compatiable with JavaScript semantics.

**Comment by abchatra** [comment]
Can we port the issue to PXT repo?

**Comment by abchatra** [comment]
Or adafruit repo. It hard to keep track of issues in another repo

**Comment by pelikhan** [comment]
Adafruit better.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
ported to adafruit repo
